#!/usr/bin/env bash
set -euo pipefail

# 入参：版本号、包构建号、目标架构、.NET Runtime ID (RID)
VERSION="${1:-0.1.0}"
PKGREL="${2:-1}"
ARCH="${3:-aarch64}"

# 映射架构对应的 .NET RID
if [ -z "${4:-}" ]; then
    case "$ARCH" in
        aarch64|arm64)
            ARCH="aarch64"
            RID="linux-musl-arm64"
            ;;
        x86_64|amd64)
            ARCH="x86_64"
            RID="linux-musl-x64"
            ;;
        *)
            ARCH="aarch64"
            RID="linux-musl-arm64"
            ;;
    esac
else
    RID="$4"
fi

PKGNAME="qqmusic-tui"
OUTPUT_FILE="${PKGNAME}-${VERSION}-r${PKGREL}.${ARCH}.apk"

echo "==> Building native AOT binary for Alpine ${ARCH} (${RID})..."
dotnet publish -c Release -r "${RID}" QQMusic.Tui.csproj

BIN_PATH="bin/Release/net10.0/${RID}/publish/QQMusic.Tui"
if [ ! -f "$BIN_PATH" ]; then
    echo "Error: Binary not found at $BIN_PATH"
    exit 1
fi

echo "==> Assembling fakeroot package directory..."
WORK_DIR=$(mktemp -d /tmp/qqmusic_apk.XXXXXX)
STAGE_DIR="$WORK_DIR/stage"
CONTROL_DIR="$WORK_DIR/control"
mkdir -p "$STAGE_DIR/usr/bin" "$CONTROL_DIR"

trap 'rm -rf "$WORK_DIR"' EXIT

cp "$BIN_PATH" "$STAGE_DIR/usr/bin/qqmusic-tui"
chmod 755 "$STAGE_DIR/usr/bin/qqmusic-tui"

if [ -d "bin/Release/net10.0/${RID}/publish/www" ]; then
    mkdir -p "$STAGE_DIR/usr/share/qqmusic-tui/www"
    cp -r "bin/Release/net10.0/${RID}/publish/www/"* "$STAGE_DIR/usr/share/qqmusic-tui/www/"
fi

INSTALLED_SIZE=$(du -sb "$STAGE_DIR/usr" 2>/dev/null | awk '{print $1}' || du -k "$STAGE_DIR/usr" | awk '{print $1 * 1024}')
BUILD_DATE=$(date +%s)

echo "==> Generating Alpine .PKGINFO metadata..."
cat << EOF > "$CONTROL_DIR/.PKGINFO"
# Generated by build-apk.sh
pkgname = ${PKGNAME}
pkgver = ${VERSION}-r${PKGREL}
pkgdesc = Linux terminal QQ Music player (.NET 10 Native AOT)
url = https://github.com/Viemean/qqmusiclinux/tree/tui
builddate = ${BUILD_DATE}
packager = Yuzuki <lxf74663@gmail.com>
size = ${INSTALLED_SIZE}
arch = ${ARCH}
license = MIT
depend = gstreamer
depend = gst-plugins-base
depend = gst-plugins-good
EOF

echo "==> Packing Alpine .apk archive..."
if command -v abuild-tar >/dev/null 2>&1; then
    tar -C "$STAGE_DIR" -c usr | abuild-tar --hash | gzip -9 > "$WORK_DIR/data.tar.gz"
    tar -C "$CONTROL_DIR" -c .PKGINFO | abuild-tar --cut | gzip -9 > "$WORK_DIR/control.tar.gz"

    KEY_FILE=""
    for k in /root/.abuild/*.rsa ~/.abuild/*.rsa; do
        if [ -f "$k" ]; then
            KEY_FILE="$k"
            break
        fi
    done

    if [ -n "$KEY_FILE" ] && command -v abuild-sign >/dev/null 2>&1; then
        echo "==> Signing package with $KEY_FILE..."
        abuild-sign -k "$KEY_FILE" "$WORK_DIR/control.tar.gz"
    fi

    cat "$WORK_DIR/control.tar.gz" "$WORK_DIR/data.tar.gz" > "$OUTPUT_FILE"
else
    tar -C "$STAGE_DIR" -czf "$WORK_DIR/data.tar.gz" usr
    tar -C "$CONTROL_DIR" -czf "$WORK_DIR/control.tar.gz" .PKGINFO
    cat "$WORK_DIR/control.tar.gz" "$WORK_DIR/data.tar.gz" > "$OUTPUT_FILE"
fi

echo "==> Alpine package generated successfully: ${OUTPUT_FILE}"
ls -lh "$OUTPUT_FILE"
